# SPDX-License-Identifier: MIT
# This task configures test systems for testing in the CI environment.
# Only use this task for testing.
# This task file resides in `tasks/` so that it can be used from other roles
# with `include_role` with `tasks_from: filename` directly without the need to
# provide a relative path. Providing relative path is problematic with
# collections.
---
- name: Make sure qnetd is not installed
  package:
    name:
      - corosync-qnetd
    state: absent
  when: not __ha_cluster_is_ostree | d(false)

- name: Make sure qnetd config files are not present
  file:
    path: /etc/corosync/qnetd
    state: absent
  when: not __ha_cluster_is_ostree | d(false)
