# SPDX-License-Identifier: MIT
---
# All required repositories are already part of SLES for SAP Applications.

# High Availability Extension (HAE) is required for cluster setup on SLES.
# All cluster packages are present on SLES_SAP and openSUSE,
# but not on base SLES without HAE.
- name: Block to assert that High Availability Extension is present on SLES
  when: ansible_distribution.split("_")[0] == 'SLES'
  block:

    - name: Query package sle-ha-release
      ansible.builtin.shell:
        cmd: rpm -q sle-ha-release
      register: __ha_cluster_sle_ha_release
      changed_when: false
      ignore_errors: true  # ignore and check /etc/products.d/ file instead

    - name: Check High Availability Extension presence using product file
      ansible.builtin.stat:
        path: /etc/products.d/sle-ha.prod
      register: __ha_cluster_sle_ha_stat
      when: __ha_cluster_sle_ha_release.rc != 0

    # Registering HA Extension results in:
    # - Created file /etc/products.d/sle-ha.prod
    # - Installed sle-ha-release package.
    # Cluster packages are not installed by default.
    - name: Assert that High Availability Extension is present
      ansible.builtin.assert:
        that:
          - __ha_cluster_sle_ha_release.rc == 0 or
            (__ha_cluster_sle_ha_stat is defined
              and __ha_cluster_sle_ha_stat.stat.exists)
        success_msg: "High Availability Extension was detected."
        fail_msg: |
          High Availability Extension is not registered!
          Register HA Extension before executing again.
      # Fatal fail will occur if any of cluster nodes is missing HAE
      any_errors_fatal: true
